FROM python:3.10-slim

ARG VENV_NAME="my_project"
ENV VENV_NAME=$VENV_NAME

RUN mkdir requirements

COPY install_requirements.sh requirements.txt requirements/

RUN bash ./requirements/install_requirements.sh $VENV_NAME
